const CAMERA_RECOGNIZE = "CAMERA_RECOGNIZE";
const CAMERA_CONNECTED = "CAMERA_CONNECTED";
const CAMERA_CONNECTING = "CAMERA_CONNECTING";
const CAMERA_DISCONNECTED = "CAMERA_DISCONNECTED";

module.exports = { 
    CAMERA_CONNECTED, 
    CAMERA_CONNECTING, 
    CAMERA_DISCONNECTED, 
    CAMERA_RECOGNIZE 
};
