export const CAMERA_RECOGNIZE = "CAMERA_RECOGNIZE";
export const CAMERA_CONNECTED = "CAMERA_CONNECTED";
export const CAMERA_CONNECTING = "CAMERA_CONNECTING";
export const CAMERA_DISCONNECTED = "CAMERA_DISCONNECTED";
